version: '3.8'

services:
  app:
    image: node:17-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && (fuser -k 3001/tcp || true) && npm start"
